# SiFli Sparks 项目配置文件
# 这个文件包含了所有要展示的SiFli芯片相关开源项目

[projects.superkey]
name = "SuperKey"
description = """
多功能宏键盘
"""
thumbnail = "iot-gateway.jpg"
tags = ["键盘"]
github_url = "https://github.com/SiFliSparks/SuperKey"
